web/app/tournament/__init__.py
from flask import Blueprint

tournament = Blueprint('tournament', __name__)

from . import tourny

web/app/views.py
import itertools

from sqlalchemy import or_, func
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from flask.ext.login import current_user
from flask.ext.security import login_required
from flask.ext.security import roles_required
from .tokengen import generate_token
from .forms import AddGameServerForm, SearchPlayerForm, AddPlayerForm
from .models import GoServer, Game, User, Player, SERVER_ADMIN_ROLE, RATINGS_ADMIN_ROLE
from . import db, user_datastore

ratings = Blueprint("ratings", __name__)

@ratings.route('/')
def home():
    return render_template('index.html')

@ratings.route('/help')
def help():
    return render_template('help.html')

@ratings.route('/myaccount')
@login_required
def myaccount():
    form = AddPlayerForm()
    form.server.choices = [(server.id, server.name) for server in GoServer.query.all()]
    players = Player.query.filter(Player.user_id == current_user.id).order_by(Player.name.asc()).all()
    # shows all games so far. Needs to be replaced with a join query that
    # orders by date played and limits to latest 10 games.
    games = itertools.chain(*(
        Game.query.filter(or_(Game.white_id == player.id, Game.black_id == player.id))
        for player in players))
    return render_template('myaccount.html', user=current_user, games=games, players=players, form=form)

@ratings.route('/games', methods=['GET'])
def listgames():
    limit = request.args.get('limit', 30)
    aga_id = request.args.get('aga_id')
    player_id = request.args.get('player_id')
    sid = request.args.get('server_id')

    players = []
    games = []

    if aga_id:
        user_ids = [tup[0] for tup in User.query.filter(User.aga_id == aga_id).with_entities(User.id).all()]
        players = Player.query.filter(Player.user_id.in_(user_ids)).all()
    elif player_id:
        players = Player.query.filter(Player.id == player_id).all()

    if players:
        for p in players:
            game_filter = ((Game.white_id==p.id) | (Game.black_id==p.id))
            if sid:
                game_filter = game_filter & (Game.server_id==sid)
            games.extend(Game.query.filter(game_filter).all())
    else:
        query = Game.query.order_by(Game.date_reported.desc()).limit(limit)
        if sid:
            query = query.filter(Game.server_id == sid)
        games = query.all()

    return render_template('latestgames.html', user=current_user, games=games)


@ratings.route('/games/<game_id>')
def gamedetail(game_id):
    game = Game.query.get_or_404(game_id)
    return render_template('gamedetail.html', user=current_user, game=game)


@ratings.route('/game_servers', methods=['GET'])
def servers():
    servers = GoServer.query.limit(30).all()
    return render_template('servers.html', user=current_user, servers=servers)

@ratings.route('/game_servers/<server_id>', methods=['GET'])
def server(server_id):
    server = GoServer.query.get_or_404(server_id)
    players = Player.query.filter(Player.server_id == server_id).limit(30).all()
    return render_template('server.html', user=current_user, server=server, players=players)

@ratings.route('/game_servers/<server_id>/reset_token', methods=['POST'])
@login_required
@roles_required(SERVER_ADMIN_ROLE.name)
def reset_server_token(server_id):
    server = GoServer.query.get_or_404(server_id)
    if not current_user.can_reset_server_token(server):
        return current_app.login_manager.unauthorized()
    server.token = generate_token()
    db.session.add(server)
    db.session.commit()
    current_app.logger.info("Reset server token for {}".format(server_id))
    return "Success"

@ratings.route('/users')
@login_required
@roles_required(RATINGS_ADMIN_ROLE.name)
def users():
    users = User.query.limit(30).all()
    return render_template('users.html', user=current_user, users=users)

@ratings.route('/players', methods=['POST'])
@login_required
def create_player():
    form = AddPlayerForm()
    form.server.choices = [(server.id, server.name) for server in GoServer.query.all()]
    if form.validate_on_submit():
        server_id = form.server.data
        name = form.name.data
        db.session.add(Player(name=name, server_id=server_id, user_id=current_user.id, token=generate_token()))
        db.session.commit()

    return redirect(url_for('ratings.myaccount'))


@ratings.route('/players/search', methods=['GET', 'POST'])
def players():
    form = SearchPlayerForm()
    player_query = Player.query

    if form.validate_on_submit():
        player_query = player_query.join(User)
        if form.player_name.data:
            player_query = player_query.filter(
                func.lower(User.name).contains(form.player_name.data.lower()))
        if form.aga_id.data:
            player_query = player_query.filter(
                User.aga_id == form.aga_id.data)

    players = player_query.limit(100).all()

    return render_template('players.html', players=players, form=form)

@ratings.route('/players/<player_id>')
def player(player_id):
    player = Player.query.get_or_404(player_id)
    games = Game.query.filter(or_(Game.white_id == player_id, Game.black_id == player_id)).all()
    return render_template('player.html', user=current_user, player=player, games=games)

@ratings.route('/players/<player_id>/reset_token', methods=['POST'])
@login_required
def reset_player_token(player_id):
    player = Player.query.get_or_404(player_id)
    if not current_user.can_reset_player_token(player):
        return current_app.login_manager.unauthorized()
    player.token = generate_token()
    db.session.add(player)
    db.session.commit()
    current_app.logger.info("Reset player token for {}".format(player_id))
    return "Success"

@ratings.route('/game_servers/new', methods=['GET', 'POST'])
@login_required
@roles_required(RATINGS_ADMIN_ROLE.name)
def create_game_server():
    form = AddGameServerForm()
    gs = GoServer()
    if form.validate_on_submit():
        gs.name = form.gs_name.data
        gs.url = form.gs_url.data
        gs.token = generate_token()
        db.session.add(gs)
        db.session.commit()
        return server(gs.id)
    return render_template('gameserver.html', form=form, gs=gs)

def user_registered_sighandler(app, user, confirm_token):
    '''
    Generate a token for the newly registered user.
    This signal handler is called every time a new user is registered.
    '''
    default_role = user_datastore.find_role('user')
    user_datastore.add_role_to_user(user, default_role)
    db.session.add(user)
    db.session.commit()

web/app/templates/base.html
{% extends "bootstrap/base.html" %}


{% block head %}
{{super()}}
<link rel="stylesheet" type="text/css" href="/static/bootstrap.min.css">
{% endblock %}
{% block title %}Online Ratings Database{% endblock %}
{% block navbar %}
<nav class="navbar nav navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-collapse collapse">
            <img class="navbar-brand" style="padding: 5px"src="/static/agalogo2.png"><a class="navbar-brand" href="/">AGA Online Ratings</a>
            <ul class="nav navbar-nav">
                <li><a href="{{url_for('ratings.home')}}">Home</a></li>
                {% if current_user.has_role('ratings_admin') %}
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Ratings Admin<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li> <a href="{{url_for('ratings.servers')}}">Game Servers</a></li>
                        <li> <a href="{{url_for('ratings.listgames')}}">Latest Games</a></li>
                        <li> <a href="{{url_for('ratings.players')}}">Players</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if current_user.has_role('server_admin') %}
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Server Admin<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li> <a href="{{url_for('ratings.servers')}}">Game Servers</a></li>
                        <li> <a href="{{url_for('ratings.listgames')}}">Latest Games</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if current_user.is_authenticated() %}
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Account<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('ratings.myaccount')}}">My Account</a></li>
                        <li><a href="{{url_for_security('change_password')}}">Change Password</a></li>
                    </ul>
                </li>
                {% endif %}
                <li><a href={{url_for('ratings.help')}}>Help</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated() %}
                <li class="navbar-text">Logged in as {{current_user.email}}</li>
                <li><a href="{{url_for_security('logout')}}">Logout</a></li>
            {% else %}
                <li><a href="{{url_for_security('register')}}">Register</a></li>
                <li><a href="{{url_for_security('login')}}">Login</a></li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% include "security/_messages.html" %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{super()}}
<script type="text/javascript">
var csrftoken = "{{ csrf_token() }}";

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
    }
})

$(function () {
    $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}

web/app/templates/gamedetail.html
{% extends "base.html" %}

{% block title %}some game{% endblock %}

{% block page_content %}

{% if game and game.game_record is not none %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"> {{ game }} </h3>
    </div>

    <div class="panel-body">
      <div id="glift" style="display:block; position:relative; width:70%; height:500px">
    </div>
  </div>

  <script src="/static/glift.min.js"></script>
  <script>

  gliftWidget = glift.create({
    sgf: "{{url_for('api.get_game_sgf', game_id=game.id)}}",
    divId: "glift",
    display: {
      theme: 'DEPTH',
      disableZoomForMobile: true
    }
  });
    </script>
  {% else %}
  <h2> No game record found </h2>
  {% endif %}
{% endblock %}

web/app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block page_content %}
<div class="jumbotron">
    <h2>
Welcome to the American Go Association's online ratings server.
</h2>
<p>
This service provides a way for AGA members to play rated games on 3rd party go servers.  The games are ranked separately from in person games and are independent of your AGA rating.
</p>
<p>
The online-ratings profile is an open protocol -- any 3rd party server can implement it.
</p>
<p>
Stay tuned for more information...
</p>
{% endblock %}

web/app/templates/latestgames.html
{% extends "base.html" %}

{% block title %}Latest Games{% endblock %}

{% block page_content %}
<table border class="table">
<tr>
    <th>Game Server</th>
    <th>White AGA ID (nick)</th>
    <th>Black AGA ID (nick)</th>
    <th>Result</th>
    <th>Date Played</th>
    <th>Date reported</th>
    <th>Game Record</th>
</tr>
{% for g in games %}
<tr>
    <td>{{g.game_server.name}}</td>
    <td>{{g.white.user.aga_id}} ({{g.white.name}})</td>
    <td>{{g.black.user.aga_id}} ({{g.black.name}})</td>
    <td>{{g.result}}</td>
    <td>{{g.date_played}}</td>
    <td>{{g.date_reported}}</td>
    <td>
    {% if g.game_record is not none %}
      <a href="{{ url_for('ratings.gamedetail', game_id=g.id) }}">link</a>
    {% endif %}
    </td>
</tr>
{% else %}
<tr><td colspan="10"><center>No games found</center></td></tr>
{% endfor %}
</table>
{% endblock %}

web/app/templates/myaccount.html
{% extends "base.html" %}

{% block title %}My Account{% endblock %}

{% block page_content %}

<h1> My Account </h1>
<table class="table">
   <tr><td>AGA ID</td>
       {% if user.aga_id is none %}
       <td><a href="{{url_for('verify.verify_form')}}"> Link your AGA account </a></td>
       {% else %}
       <td>{{ user.aga_id }}</td>
       {% endif %}
    </tr>
    <tr><td>Contact Email</td><td>{{ user.email }}</td></tr>
    <tr><td>Rating</td><td> {{ user.last_rating() or "No rating available"}}</td></tr>
    <!-- User ID: {{user.id}} -->
</table>

{% if user.is_server_admin() %}
<h2>My Game Server(s)</h2>
<table class="table">
    <tr><th>Name</th><th>URL</th><th>Token</th></tr>
    {% for s in user.servers %}
    <tr>
        <td>{{ s.name }}</td>
        <td>{{ s.url }}</td>
        <td>{{ s.token }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

<h2> My profiles </h2>

<div class="panel panel-default">
    <table class="table">
        <tr>
            <th>Server</th>
            <th>Name <a href="#" data-toggle="tooltip" title="This is your nickname or handle on the server">?</a> </th>
            <th>Token <a href="#" data-toggle="tooltip" title="Anyone with your token can play rated games as this profile.  Keep it secret!">?</a> &nbsp; <a href="#"id="show-token-button" onClick="showTokens()">(Show tokens)</a></th>
            <th>Reset token <a href="#" data-toggle="tooltip" title="Reset this token - games will stop being submitted until you re-enter your new token">?</a></th></tr>
        {% for p in players %}
        <tr>
            <td>{{p.server.name}}</td>
            <td>
                <a href="{{ url_for('ratings.player', player_id=p.id) }}">{{p.name}}</a>
            </td>
            <td><div class="player-token" style="display:none">{{ p.token }}</div></td>
            <td><button onclick="reset_token({{p.id}})" type="button">Reset</td>
        </tr>
        {% else %}
        <tr><td colspan="4">No profiles yet! To get started, create a profile below. </td></tr>
        {% endfor %}
    </table>
</div>

<form method="POST" action="{{ url_for('ratings.create_player') }}">
    {{form.csrf_token}}
    Username {{form.name}} on server {{form.server}}
    <input type="submit" value="Create profile"/>

</form>


<h2>My Games</h2>
<div class="panel panel-default">
<table class="table">
  <tr>
    <th>Game Server</th>
    <th>White</th>
    <th>Black</th>
    <th>Result</th>
    <th>Date Played</th>
    <th>Game Record</th>
  </tr>
{% for g in games %}
  <tr>
    <td>{{g.game_server.name}}</td>
    <td>
      <a href="{{url_for('ratings.player', player_id=g.white.id)}}">
      {% if g.result.upper().startswith('W') %}
          <strong>AGA {{g.white.user.aga_id}} ({{g.white.name}})</strong>
      {% else %}
          AGA {{g.white.user.aga_id}} ({{g.white.name}})
      {% endif %}
      </a>
    </td>
    <td>
      <a href="{{url_for('ratings.player', player_id=g.black.id)}}">
      {% if g.result.upper().startswith('B') %}
          <strong>AGA {{g.black.user.aga_id}} ({{g.black.name}})</strong>
      {% else %}
          AGA {{g.black.user.aga_id}} ({{g.black.name}})
      {% endif %}
      </a>
    </td>
    <td>{{g.result}}</td>
    <td>{{g.date_played}}</td>
    <td><a href="{{url_for('ratings.gamedetail', game_id=g.id)}}">link</a></td>
  </tr>
{% else %}
  <tr><td colspan="6">No games played yet.</td></tr>
{% endfor %}
</table>

</div>

{% endblock %}
{% block scripts %}
{{super()}}
<script type="text/javascript">
function showTokens() {
    $('div.player-token').removeAttr('style');
    $('#show-token-button').remove();
}

function reset_token(player_id) {
    var TOKEN_RESET_ENDPOINT = "{{ url_for('ratings.reset_player_token', player_id='replacethis') }}";
    return $.ajax({
        method: "POST",
        url: TOKEN_RESET_ENDPOINT.replace("replacethis", player_id)
    }).then(function(response) {
        alert("Token successfully reset.")
        location.reload();
    }).fail(function(response) {
        alert("Uhoh, something went wrong. Please contact an admin.")
    });
}
</script>{% endblock %}

web/app/templates/player.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Home{% endblock %}

{% block page_content %}

<h1>{{player.user.name}}</h1>

<table border class="table">
    <tr><td>AGA ID</td><td>{{ player.user.aga_id }}</td></tr>
    <tr><td>Server</td><td>{{ player.server.name }}</td></tr>
</table>
<table border class="table">
  <tr>
    <th>Game Server</th>
    <th>White</th>
    <th>Black</th>
    <th>Result</th>
    <th>Date Played</th>
    <th>Game Record</th>
  </tr>
{% for g in games %}
  <tr>
    <td>{{g.game_server.name}}</td>
    <td>
      <a href="{{url_for('ratings.player', player_id=g.white.id)}}">
      {% if g.result.upper().startswith('W') %}
          <strong>AGA {{g.white.user.aga_id}} ({{g.white.name}})</strong>
      {% else %}
          AGA {{g.white.user.aga_id}} ({{g.white.name}})
      {% endif %}
      </a>
    </td>
    <td>
      <a href="{{url_for('ratings.player', player_id=g.black.id)}}">
      {% if g.result.upper().startswith('B') %}
          <strong>AGA {{g.black.user.aga_id}} ({{g.black.name}})</strong>
      {% else %}
          AGA {{g.black.user.aga_id}} ({{g.black.name}})
      {% endif %}
      </a>
    </td>
    <td>{{g.result}}</td>
    <td>{{g.date_played}}</td>
    <td><a href="{{url_for('ratings.gamedetail', game_id=g.id)}}">link</a></td>
  </tr>
{% else %}
  <tr><td colspan="6">No games played under this profile.</td></tr>
{% endfor %}
</table>


{% endblock %}

web/app/templates/servers.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Servers{% endblock %}

{% block page_content %}

{% if servers %}
<table border class="table">
  <tr><th>server_id</th><th> Name </th> <th> URL </th> <th> Players </th> </tr>
  {% for gs in servers %}
  <tr>
    <td>{{gs.id}}</td>
    <td><a href="{{ url_for('ratings.server', server_id=gs.id) }}"> {{ gs.name}} </a></td>
    <td>{{ gs.url }}</td>
    <td>{{ gs.players|length }}</td></tr>
    {%endfor%}
</table>
{% endif %}

{% if current_user.has_role('ratings_admin') %}
<h2><a href="{{ url_for('ratings.create_game_server')}}"> Add Server </a> </h2>
{% endif %}

{% endblock %}

web/app/templates/tournament_block.html
<div>
  <h3>Event Name: {{ tournament.event_name }}</h3>
  <ul>
    {% if tournament.venue %}
      <li>Venue: {{ tournament.venue }}</li>
      <li>Venue Address: {{ tournament.venue_address }}</li>
      <li>Venue State: {{ tournament.venue_state }}</li>
      <li>Venue Zip: {{ tournament.venue_zip }}</li>
    {% endif %}

    <li>Start Date: {{ tournament.start_date }}</li>
    {% if tournament.end_date %}
      <li>End Date {{ tournament.end_date }}</li>
    {% endif %}

    <li>Director: {{ tournament.director }}</li>
    <li>Director Email: {{ tournament.director_email }}</li>
    {% if tournament.phone %}
      <li>Director Phone: {{ tournament.director_phone }}</li>
    {% endif %}
    {% if tournament.director_address %}
      <li>Director Address : {{ tournament.director_address }}</li>
    {% endif %}


    {% if tournament.sponsor %}
      <li>Sponsor: {{ tournament.sponser }}</li>
      <li>Sponsor Email: {{ tournament.sponser_email }}</li>
      <li>Sponsor Phone: {{ tournament.sponser_phone }}</li>
      <li>Sponsor Website: {{ tournament.sponser_website }}</li>
      <li>Sponsor Address: {{ tournament.sponser_address }}</li>
    {% endif %}

    {% if tournament.convener %}
      <li>Convener: {{ tournament.convener }}</li>
      <li>Convener Email: {{ tournament.convener_email }}</li>
      <li>Convener Phone: {{ tournament.convener_phone }}</li>
      <li>Convener Website: {{ tournament.convener_website }}</li>
      <li>Convener Address: {{ tournament.convener_address }}</li>
    {% endif %}

    <li>Pairing: {{ tournament.pairing }}</li>
    <li>Rules: {{ tournament.rule_set }}</li>
    <li>Time Controls: {{ tournament.time_controls }}</li>
    <li>Basic Time: {{ tournament.basic_time }}</li>
    <li>Overtime Format: {{ tournament.overtime_format }}</li>
    <li>Overtime Conditions: {{ tournament.overtime_conditions }}</li>

    <li>Komi: {{ tournament.komi }}</li>

    <li>Tie Break Tier 1: {{ tournament.tie_break1 }}</li>
    <li>Tie Break Tier 2: {{ tournament.tie_break2 }}</li>

    <li>Submitted: {{ tournament.submitted }}</li>

  </ul>
  <p>
    {% if request.path != url_for('.show', tournament_id=tournament.id) %}
    <a href="{{ url_for('.show', tournament_id=tournament.id) }}"><button>Details</button></a>
    {% endif %}
    {% if tournament.submitted == False %}

      <a href="{{ url_for('.edit_tournament', tournament_id=tournament.id) }}"><button>Edit</button></a>
    {% endif %}
      <a href="{{ url_for('.new_player', tournament_id=tournament.id) }}"><button>Add Player</button></a>
      <a href="{{ url_for('.players_index', tournament_id=tournament.id) }}"><button>View Players</button></a>
  </p>
</div>

web/app/templates/tournament_form.html
{% extends 'base.html' %}



{% block content %}
<div class="container">
<h2>Please enter Tournament Info:</h2>

<!--  if new  else edit -->
  <form method="post" name='/' {% if not tournament %}
    action="{{ url_for('.index') }}" > {% endif %}

    {% if tournament %}
      action="{{ url_for('.show', tournament_id=tournament.id) }}" >
        <input type="hidden" name="_method" value="PUT">
        <!--  Using HTML Forms for PUT and DELETE require smuggling those 
              values in as hidden inputs on POST requests.
              Ajax could be used to clean this up -->
    {% endif %}

    {{ form.hidden_tag() }}

        <p>{{ form.event_name.label }}: {{ form.event_name }}</p>

        <!-- venue details -->
        <p>{{ form.venue.label }}: {{ form.venue }}</p>
        <p>{{ form.venue_address.label }}: {{ form.venue_address }}</p>
        <p>{{ form.venue_state.label }}: {{ form.venue_state }}</p>
        <p>{{ form.venue_zip.label }}: {{ form.venue_zip }}</p>

        <!--  tourny dates-->
        <p>{{ form.start_date.label }}: {{ form.start_date }}</p>
        <p>{{ form.end_date.label }}: {{ form.end_date }}</p>

        <p>{{ form.director.label }}: {{ form.director }}</p>
        <p>{{ form.director_email.label }}: {{ form.director_email }}</p>
        <p>{{ form.director_phone.label }}: {{ form.director_phone }}</p>
        <p>{{ form.director_address.label }}: {{ form.director_address }}</p>

        <p>{{ form.sponsor.label }}: {{ form.sponsor }}</p>
        <p>{{ form.sponsor_phone.label }}: {{ form.sponsor_phone }}</p>
        <p>{{ form.sponsor_email.label }}: {{ form.sponsor_email }}</p>
        <p>{{ form.sponsor_website.label }}: {{ form.sponsor_website }}</p>
        <p>{{ form.sponsor_address.label }}: {{ form.sponsor_address }}</p>

        <p>{{ form.convener.label }} {{ form.convener }}</p>
        <p>{{ form.convener_phone.label }}: {{ form.convener_phone }}</p>
        <p>{{ form.convener_email.label }}: {{ form.convener_email }}</p>
        <p>{{ form.convener_website.label }}: {{ form.convener_website }}</p>
        <p>{{ form.convener_address.label }}: {{ form.convener_address }}</p>

        <p>{{ form.pairing.label }}: {{ form.pairing }}</p>

        <p>{{ form.rule_set.label }}: {{ form.rule_set }}</p>

        <p>{{ form.time_controls.label }}: {{ form.time_controls }}</p>
        <p>{{ form.basic_time.label }}: {{ form.basic_time }}</p>
        <p>{{ form.overtime_format.label }}: {{ form.overtime_format }}</p>
        <p>{{ form.overtime_conditions.label }}:
            {{ form.overtime_conditions }}</p>

        <p>{{ form.komi.label }}: {{ form.komi }}</p>
        <p>{{ form.tie_break1.label }}: {{ form.tie_break1 }}</p>
        <p>{{ form.tie_break2.label }}: {{ form.tie_break2 }}</p>

        <p>Check to Submit Finalized Tournament Record:
            {{ form.submitted }}</p>
        <p>{{ form.submit }}</p>
  </form>
</div>

{% endblock content %}

web/app/templates/tournament_match_form.html
{% extends "base.html" %}

{% block content %}
  <div class="container">


    <form action="{{ url_for('.match', tournament_id=match.tournament_id, match_id=match.id) }}" method="post">
      <input type="hidden" name="_method" value="PUT">
      <!--  Using HTML Forms for PUT and DELETE require smuggling those
            values in as hidden inputs on POST requests.
            Ajax could be used to clean this up -->
      {{ form.hidden_tag() }}
      <p>{{ form.player_1_name.label }} {{ form.player_1_name }}</p>
      <p>{{ form.player_2_name.label }} {{ form.player_2_name }}</p>
      <p>{{ form.result.label }}  {{ form.result }}</p>
      <p>{{ form.result_notation.label }}  {{ form.result_notation }}</p>
      <p>{{ form.pairing.label }}  {{ form.pairing }}</p>
      <p>{{ form.submit }}</p>
    </form>
    </div>

{% endblock content %}

web/app/templates/tournament_matches_by_round.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>Round {{ matches[0].t_round }}</h1>
  {% for match in matches %}
  <div>
    <p>Match ID {{ match.id }}</p>
    <p>Black's Name: {{ match.player_1_name}}</p>
    <p>White's Name: {{ match.player_2_name }}</p>
    <p>Match Pairing: {{ match.pairing }}</p>
    <p>Match Result: {{ match.result }}</p>
    <p>Match Result Notation: {{ match.result_notation }}</p>
    {% if match.tourny_round.submitted == False %}
      <a href="{{ url_for('.edit_match', tournament_id=match.tournament_id, match_id=match.id)}}"><button type="button" name="button">Edit Match</button></a>
    {% endif %}
    </br></br>
  </div>
  {% endfor %}

<!--  why???-->
{% if matches[0].tourny_round.submitted == True and
  latest_round %}
  <form action="{{ url_for('.full_pairing',
                   tournament_id=tournament_id) }}" method="POST">
    <!-- <input type="submit" value="Pair for Next Round"> -->
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <button type="submit">Pair for Next Round</button>
  </form>
{% endif %}

<!--  if round being viewed is not currently open round; link to next round-->
{% if matches[0].tourny_round.submitted == True %}
  <a href="{{ url_for('.matches_by_round_index', tournament_id=tournament_id,
              round_id=(matches[0].t_round + 1)) }}">
              <button type="button">View Next Round</button></a>
{% endif %}

{% if matches[0].tourny_round.submitted == False %}

  <form action="{{ url_for('.submit_round',
                   tournament_id=tournament_id,
                   round_id=matches[0].t_round) }}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <button type="submit">Submit Round</button>
  </form>
{% endif %}

</div>
{% endblock content%}